apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.entity_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - mvc
  links:
    - url: http://localhost:${{values.port_number}}/${{values.entity_name}}SpringBootCRUDProj/
      title: ${{values.entity_name}} Website
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.entity_name}}
#  consumesApis:
#    - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.entity_name }}
  description: ${{ values.description }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/${{values.entity_name}}SpringCRUDProj/src/main/resources/api-docs.yaml